export enum ReportTypeEnum {
  RECEIVABLES = 'RECEIVABLES',
  ASSET_PORTFOLIO = 'ASSET_PORTFOLIO',
  LIABILITY_PORTFOLIO = 'LIABILITY_PORTFOLIO',
  CONSOLIDATED_AQUISITION = 'CONSOLIDATED_ACQUISITION',
  MARKET = 'MARKET',
  LIQUIDADOS_BAIXADOS = 'LIQUIDADOS_BAIXADOS',
  LIQUIDADOS_BAIXADOS_V2 = 'LIQUIDADOS_BAIXADOS_V2',
  MOVIMENTO_ABERTO = 'MOVIMENTO_ABERTO',
}
