export enum MarketTypeEnum {
  OutrosFundos = 'outros-fundos',
  RendaFixa = 'rf',
  RendaVariavel = 'rv',
  Rentabilidade = 'rentabilidade',
  Futuros = 'futuros',
  RvOpcoes = 'rv-opcoes',
  RvOpcoesFlexiveis = 'rv-opcoes-flexiveis',
  Swap = 'swap',
  Termo = 'termo',
  TermoReverse = 'termo-reverse',
  Cambio = 'cambio',
  CPR = 'cpr',
  Tesouraria = 'tesouraria',
  ContaCorrente = 'conta-corrente',
  OpcoesFuturo = 'opcoes-futuro',
  OutrosAtivos = 'outros-ativos',
  OutrosEmprestimos = 'outros-emprestimos',
  RFFindCursor = 'rf-find-cursor',
  RFCompromissadadas = 'rf-compromissadadas',
  RVEmprestimoAcoes = 'rv-emprestimo-acoes',
  RVEmprestimoAcoesInadimplentes = 'rv-emprestimo-acoes-inadimplentes',
  MEC = 'mec',
  DemonstrativoCaixa = 'demonstrativo-caixa',
}
